info: |
  Статистику по многим параметрам можно сформировать с помощью
  <a href='http://gitstats.sourceforge.net/'>gitstats</a>
ft: bash
order: [41]
links:
  - ['http://www-cs-students.stanford.edu/~blynn/gitmagic/intl/ru/', 'Мануал по гиту']
