name: Common Lisp
ft: lisp
notes: |
  Формат для примеров по Common Lisp отличается от того что используется в
  большинстве своём в других разделах. Вывод и возвращаемые значения функций
  должны быть в блоке code, отделённые '; '.
links:
  - [http://www.lispmachine.net/, 'сборник ссылок на интересные материалы по Common Lisp']
  - [http://lisper.ru/, 'наверное единственный сайт по Common Lisp в рунете']
  - [http://cl-cookbook.sourceforge.net/, 'сборник рецептов по Common Lisp']
  - [http://www.gigamonkeys.com/book/, 'Practical Common Lisp - великолепная книга с реальными примерами использования CL']
  - [http://pcl.catap.ru/doku.php, русский перевод PCL]
