title: Как пользоваться vim
info: |
  David Rayner (<a href='http://www.squidoo.com/zzapper'>zzapper</a>) 15 
  Years of Vi + 7 years of Vim and still learning &copy; &larr; O_O 
  
links: 
- [http://www.rayninfo.co.uk/vimtips.html, 'лучшие подсказки по vim']
