info: |
  Если в текущей директории есть скрытые каталоги, то вывод команд будет
  различаться. Первая будет искать везде, а вторая - проигнорирует скрытые
  папки на текущем уровне:
  <code><pre><b>find .
  find *</b></pre></code>
links:
  - [ 'http://find.unixpin.com/ru/', 'Генератор команды find']
