name: Перевод строки
info: |
  <pre>
  Как говорит <a href='http://en.wikipedia.org/wiki/Newline#Representations'>википедия</a>:

  CR+LF: Microsoft Windows, DEC TOPS-10, RT-11 and most other early non-Unix
         and non-IBM OSes, CP/M, MP/M, DOS (MS-DOS, PC-DOS, etc.), Atari TOS,
         OS/2, Symbian OS, Palm OS
  LF+CR: Acorn BBC spooled text output.
  CR:    Commodore 8-bit machines, Acorn BBC, TRS-80, Apple II family,
         Mac OS up to version 9 and OS-9
  LF:    Multics, Unix and Unix-like systems (GNU/Linux, AIX, Xenix, Mac OS X,
         FreeBSD, etc.), BeOS, Amiga, RISC OS, and

  Как резюмирует это <a href='http://stackoverflow.com/questions/426397/do-line-endings-differ-between-windows-and-linux'>stackoverflow</a>:
  Windows: '\r\n'
  Mac (OS 9-): '\r'
  Mac (OS 10+): '\n'
  Unix/Linux: '\n'
  </pre>
