name: ImageMagick
info: |
  <p>
    <b>mogrify</b> и <b>convert</b> - утилиты входящие в состав imagemagick. Они
    принимают одинаковые ключи, но <b>mogrify</b> - производит операции над самим
    файлом.
  </p>
  <p>
    <ul>
      <li><b>mogrify</b> - произвести действия над самим изображением</li>
      <li><b>convert</b> - произвести действия над изображением и сохранить в другой файл</li>
      <li><b>display</b> - вывести изображение на экран</li>
      <li><b>animate</b> - вывести анимированное изображение на экран</li>
    </ul>
  </p>
links: 
  - [http://www.imagemagick.org/Usage/, 'Основной источник информации по использованию IM. С картинками']
