info: |
  <b>mogrify</b> и <b>convert</b> - утилиты входящие в состав imagemagick. Они
  принимают одинаковые ключи, но <b>mogrify</b> - производит операции над самим
  файлом.
links: 
  - [http://www.imagemagick.org/Usage/, 'Основной источник информации по использованию IM. С картинками']
