info: |
  Глобальные настройки пользователя хранятся в ~/.gitconfig<br>
  Для задания настроек есть 2 пути:
  1) Команда: $ git config --global color.diff "auto"
  2) Запись в файле ~/.gitconfig:
  [color]
    diff = auto
  Результат будет идентичным - в файле ~/.gitconfig появится новая строчка.