info: |
  git bisect позволяет удобно находить баги среди коммитов.<br><br>
  2 коммита помечаются как плохой и хороший.
  Гит переводит репозиторий на середину истории между ними 
  и даёт возможность проверить - есть ли баг в данный моммент. 
  Дальше поиск производится по оставшейся половине истории.
