links:
  - [http://diveintopython3.org/, 'Хорошая книга по питону']
  - [http://hyperpolyglot.org/scripting, 'сравнение между php-perl-python-ruby']
  - [http://stackoverflow.com/questions/101268/hidden-features-of-python, 'Куча фич питона']
