info: |
  Мощная программа для архивации файловых систем.
  Работает не с байтами а с файлами, поэтому гораздо быстрее
  чем "dd if=/dev/sda of=/mnt/disk/backup.dd", плюс сжимает файлы,
  причем довольно сильно. В одном образе умеет хранить несколько томов.
  Поддерживает почти все современные файловые системы, снять образ
  можно с большого раздела, а записать в меньший, лишь бы места
  для файлов хватило.
ft: bash
links: 
  - [http://fsarchiver.org, официальный сайт программы]
